services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    networks:
      - pdf-local-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  pdf-maker:
    container_name: pdf-maker
    image: pdf-maker
    tty: true
    env_file: ../.env
    restart: always
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/opt/app
    networks:
      - pdf-local-network

networks:
  pdf-local-network:
    name: pdf-local-network
    external: true